### ISSUE TITLE
Tumor-only mode

### ISSUE THREAD

**Issue by Dagsbio** [ExpressionAnalysis/CNV_Radar#16]
Hi,

Is there any way to run cnv radar in tumor-only mode? 

If so, how should I write the running command properly?

Thank you!

**Comment by jkstrat** [comment]
Hi Dagsbio,

It is not possible to run CNV Radar on a single tumor-only sample. However, you can "unofficially" run CNV Radar on a cohort of tumor only samples. 

CNV Radar requires a reference panel in order to run. However, in the tumor-only situation you need to create the reference panel using the tumor samples. The copy neutral depth for each ROI is biased (probe affinity, GC content, mapping, ...) and variable. Using a multi-sample reference panel helps capture the extent of the variability and bias to get the best prediction at what copy neutral should be. 

CNV Radar uses the reference panel to predict what the copy neutral depth would be for the target sample at each ROI. This prediction model takes into account the association between the read depths of the target sample and each sample on the reference panel. So, obviously the target sample can't be in the reference panel. So you will need to go into the CNV_Radar.r script and uncomment lines 229-232 to remove it, if you included the target sample when creating the reference panel. 

However, a reference panel composed of tumors is bound to have some CNVs, won't that mess things up? Yes, it could. However, the association between the target and reference sample should decrease when the reference has a CNV. This will result in less influence of the read depth for that reference sample when calculating the predicted copy neutral depth for the target. So this shouldn't have a big impact, especially if the reference panel has lots of samples. 

The main issue to watch out for arises when the majority (or at least multiple) of the reference samples are not copy neutral at the same location. If every sample on the panel has a heterozygous deletion, the model assumes that the reported depth of the deletion is actually the copy-neutral depth for that region. Thus, a subsequent copy-neutral diploid sample will erroneously look like an amplification. So as long as you carefully select the tumors you use for the reference you can get a pretty reasonable estimate of the copy number variants from tumor-only samples. 

Steps: 
1. Carefully select the tumor samples to include on the reference panel
2. Create the reference panel using the CNV_Radar_create_control.r script
3. Uncomment lines 229-232 of the CNV_Radar.r script
4. Run CNV_Radar.r as you normally would

Hope this helps.

**Comment by Dagsbio** [comment]
Thanks jkstrat for your detailed explanation.

Will try soon!
