### ISSUE TITLE
Performance of CNV Radar on Difficult Samples

### ISSUE THREAD

**Issue by rsteinfe1** [ExpressionAnalysis/CNV_Radar#8]
Hi,

thank you for making CNV Radar on GitHub. I was able to get this to run with some slight modifications and I have a few questions. Is there a reason you used UnifiedGenotyper for calling SNPs? UnifiedGenotyper is pretty outdated and the Broadinstitue recommends HaplotypeCaller. Given that you only use common SNPs, wouldn't HaplotypeCaller give better allelic frequency estimates and be available in GATK4 ? 

Do you know how CNV Radar performs on Targeted Sequencing data, i.e. a few hundred genes rather than WES data. 
How robust is CNV Radar when sample quality is quite poor, such as DNA obtained from FFPE tissue samples? Would you recommend use and/or would you recommend the default settings or change any parameters or thresholds?

Thank you very much for your support.

**Comment by jkstrat** [comment]
rsteinfe1,

I'm glad that you were able to get it work. Can you tell me what the modifications were that you needed to make to get it to work?

Regarding the UnifiedGenotyper, that stems from a historic prospective. When we started the development of the project the data that we received was collected during an earlier study. Variant calling was done using UnifiedGenotyper so we needed to support that output specifically to complete the project at hand. However, the latest release supports reading in any VCF file v4.2 formatted file. The use of HaplotypeCaller should be fine to generate the appropriate inputs. 

We built CNV Radar to address CNV calling on large targeted panels rather than small targeted panels. The validation testing that we performed was on larger targeted panels (whole exome) so I don't have any data to say how well the software performs on really small panels. If you have any samples with known truth that would be something worth looking into further. With that caveat, I can't think of any technical reason why CNV Radar wouldn't work on a small panel, but I can't make any claims about accuracy.

The robustness of CNV Radar for low quality samples depends on the use of the reference panel. We highly recommend creating the reference panel from presumed copy neutral samples that were processed similarly to your target samples (procured, stored, transported, isolation, sequenced, ...) This will help account for most of that bias. However, we do know that there is a wide range of qualities for a given FFPE sample. You may see decreased sensitivity and specificity depending on how badly degraded the material is. However, we have run FFPE samples (with default parameters) during our testing and found that it performs pretty well.

Regards,
Jeran
